---
# TEST-NET-1 (192.0.2.0/24) RFC2544
usb0_interface_cidr: "192.0.2.0/29"
usb1_interface_cidr: "192.0.2.8/29"
# IPv6 Address Prefix for Documentation (2001:db8::/32) RFC3849
usb0_interface_cidr6: "" # "2001:0db8:0:0:0::0/64" # First /64
usb1_interface_cidr6: "" # "2001:0db8:0:0:1::0/64" # Second /64

# Wifi Settings
wifi_country: "GB"
wifi:
  example:
    psk: abc123def456
  "quoted example":
  low_priority:
    psk: 123456
    priority: -999
  named:
    psk: abc123
    id: Some named SSID

# Hostname & FQDN
hostname: pi
dns_name: pirouter
